image: drupalpod/drupalpod-gitpod-base:20240419

# ddev and composer are running as part of the prebuild
# when starting a workspace all docker images are ready
tasks:
  - init: |
      ddev config --web-environment-add="FRONTEND_REPOSITORY=${FRONTEND_REPOSITORY:-https://github.com/drunomics/lupus-decoupled-nextjs-demo}"
      ddev config --web-environment-add="FRONTEND_BRANCH=${FRONTEND_BRANCH:-LDP-2616-gitpod-link}"
      ddev config --web-environment-add="NEXT_PUBLIC_DRUPAL_BASE_URL=$(gp url 8080)"
